framework:
    messenger:
        transports:
            async:
                dsn: "amqp://guest:guest@vdm_training_02_rabbitmq:5672/%2f"
                options:
                    auto_setup: "true"
                    heartbeat: "60"
                    read_timeout: "60"
                    write_timeout: "60"
                    prefetch_count: "1"
                    queues:
                        "async_queue": ~

        routing:
            App\Message\AsyncActionMessage: async
